# Base configs
baseurl: "https://foto.lhzhang.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "rusty shutter"
subtitle: ""
author: "Linghua Zhang"
header:
 title: "rusty shutter"
 subtitle: "by Linghua Zhang"
footer:
 name: ""
 bio: ""
 github: ""
web_design: "AJ"
social_urls:
  facebook: ""
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: ""
